### ISSUE TITLE
Migrate to python 3

### ISSUE THREAD

**Issue by ellcs** [codingo/NoSQLMap#102]
This is a copy of the issue #97. That ticked was closed because of no issue activity. I could not reopen it.

> Hello there!
> Thank you for working on this project! Python 2 reached end of life at the end of 2019. So NoSQLMap should really migrate to python 3.
>
> Best regards, ellcs

**Comment by drwetter** [comment]
I second that!

**Comment by hastalamuerte** [comment]
fully accepted this opinion
Your project (nosqlmap) is great guys!

**Comment by blshkv** [comment]
Ping! before it got closed again

**Comment by blshkv** [comment]
ping!

**Comment by blshkv** [comment]
wtf
