### ISSUE TITLE
Wont install on latest version of kali linux 

### ISSUE THREAD

**Issue by Darkcast** [codingo/NoSQLMap#108]
## What's the problem (or question)?
when running it on kali 2020 default configuration
gave me this error

root@kali:/home/kali/NoSQLMap# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import find_packages, setup
ImportError: No module named setuptools

## How can we reproduce the issue?
run kali on 5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-2kali1 (2020-06-10) x86_64 GNU/Linux

## What are the running context details?
ran it as root using python setup.py install

**Comment by blshkv** [comment]
https://github.com/codingo/NoSQLMap/issues/102
