### ISSUE TITLE
Error Running

### ISSUE THREAD

**Issue by zufan-yp** [codingo/NoSQLMap#118]
## How can we reproduce the issue?

1. 
![image](https://user-images.githubusercontent.com/78656480/117097096-f0b39c80-ad94-11eb-9629-26ef05323c50.png)

2. 
![image](https://user-images.githubusercontent.com/78656480/117097114-f7421400-ad94-11eb-9780-08b48b3ea960.png)

3.
4.

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Microsoft Windows 10`)
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 
* Target DBMS (e.g. `Mongo`): 
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`):
* Results of manual target assessment
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by MrrRaph** [comment]
Just use Python2 it is build for Python 2.6/2.7 or use Docker
