### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by EXCISIONMODZ** [codingo/NoSQLMap#123]
what am i doing wrong im using kali linux 2021.2
┌──(root💀kali)-[~/NoSQLMap]
└─# python nosqlmap.py     
Traceback (most recent call last):
  File "nosqlmap.py", line 8, in <module>
    import nsmcouch
  File "/root/NoSQLMap/nsmcouch.py", line 6, in <module>
    import couchdb
ImportError: No module named couchdb

**Comment by Deve-OP** [comment]
Traceback (most recent call last):
  File "nosqlmap.py", line 8, in <module>
    import nsmcouch
  File "/home/developer/TOOLS/SQL INJECT/NoSQLMap/nsmcouch.py", line 6, in <module>
    import couchdb
ImportError: No module named couchdb

**Comment by Deve-OP** [comment]
convert the python2 code to 3. I think the code is written in python2 but converting it work for me

Enter this in the same directory:
2to3 . -w  

NOTE: you need to install 2to3 module before u can convert it

**Comment by Deve-OP** [comment]
convert the python2 code to 3. I think the code is written in python2 but converting it work for me

Enter this in the same directory:
2to3 . -w  

NOTE: you need to install 2to3 module before u can convert it
