### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by hazeyez** [codingo/NoSQLMap#130]
any ideas what to do here? 

i also tried python3 to install, same thing and you can see i used "sudo" the second time, to get over the permission denied error the first time.

`$ cat /etc/os-release 
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION="2022.4"
                                                                                                                  
┌──(haze㉿kali)-[~/hacking/tools/NoSQLMap]
└─$ echo $SHELL           
/usr/bin/zsh`

`┌──(haze㉿kali)-[~/hacking/tools/NoSQLMap]
└─$ python setup.py install                                                                                   1 ⨯
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:146: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/test-easy-install-69213.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.10/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.

                                                                                                                  
┌──(haze㉿kali)-[~/hacking/tools/NoSQLMap]
└─$ sudo python setup.py install                                                                              1 ⨯
[sudo] password for haze: 
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:146: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing NoSQLMap.egg-info/PKG-INFO
writing dependency_links to NoSQLMap.egg-info/dependency_links.txt
writing entry points to NoSQLMap.egg-info/entry_points.txt
writing requirements to NoSQLMap.egg-info/requires.txt
writing top-level names to NoSQLMap.egg-info/top_level.txt
reading manifest file 'NoSQLMap.egg-info/SOURCES.txt'
adding license file 'COPYING'
writing manifest file 'NoSQLMap.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/exception.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/nsmcouch.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/nsmmongo.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/nsmweb.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/nosqlmap.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/nsmscan.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/exception.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/nsmcouch.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/nsmmongo.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/nsmweb.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/nosqlmap.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/nsmscan.py to 755
copying NoSQLMap.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying NoSQLMap.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying NoSQLMap.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying NoSQLMap.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying NoSQLMap.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying NoSQLMap.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/NoSQLMap-0.7-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing NoSQLMap-0.7-py3.10.egg
Removing /usr/local/lib/python3.10/dist-packages/NoSQLMap-0.7-py3.10.egg
Copying NoSQLMap-0.7-py3.10.egg to /usr/local/lib/python3.10/dist-packages
NoSQLMap 0.7 is already the active version in easy-install.pth
Installing exception.py script to /usr/local/bin
Installing nosqlmap.py script to /usr/local/bin
Installing nsmcouch.py script to /usr/local/bin
Installing nsmmongo.py script to /usr/local/bin
Installing nsmscan.py script to /usr/local/bin
Installing nsmweb.py script to /usr/local/bin
Installing NoSQLMap script to /usr/local/bin

Installed /usr/local/lib/python3.10/dist-packages/NoSQLMap-0.7-py3.10.egg
Processing dependencies for NoSQLMap==0.7
Searching for pymongo==2.7.2
Reading https://pypi.org/simple/pymongo/
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Downloading https://files.pythonhosted.org/packages/8e/34/4b3cd4bfe5f3bfbd89873c8e24e091a6a6510c57fedea76161530be18a61/pymongo-2.7.2.tar.gz#sha256=8fb45e3edec006f4b11580fc579bec7781a8b3201ce0abf31593f086070e51f6
Best match: pymongo 2.7.2
Processing pymongo-2.7.2.tar.gz
Writing /tmp/easy_install-bgpgu937/pymongo-2.7.2/setup.cfg
Running pymongo-2.7.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-bgpgu937/pymongo-2.7.2/egg-dist-tmp-kzkkkyk8
error: Setup script exited with error in pymongo setup command: use_2to3 is invalid.
`

**Comment by grav3m1nd-byte** [comment]
Install issues are all over the place as this project is still on Python2.7 which is not "used" anymore in distros like Kali.
