### ISSUE TITLE
bug in your code

### ISSUE THREAD

**Issue by TB-JEHAD** [codingo/NoSQLMap#136]
## What's the problem (or question)?
installation problem

you mistake so much in your code , specially every print function . please solve that problem.
![Screenshot_2023-08-16_00-05-50](https://github.com/codingo/NoSQLMap/assets/104494286/d4d25631-f244-46d3-860e-590e650aa28a)
![Screenshot_2023-08-16_00-06-19](https://github.com/codingo/NoSQLMap/assets/104494286/2e1cd9d2-40f1-4581-af2f-a89e2b123e00)
![Screenshot_2023-08-16_00-07-00](https://github.com/codingo/NoSQLMap/assets/104494286/3aa8b46c-8a05-4855-a3a5-7ba03c42fd70)

**Comment by jeremylaratro** [comment]
@TB-JEHAD  You're trying to run python2 code with python3

**Comment by beune** [comment]
This is a python2 script. Please run as python2.

**Comment by mrdragonblack** [comment]
![Screenshot (41)](https://github.com/codingo/NoSQLMap/assets/118146225/81569ca5-f09d-42ef-b2f6-4a2a8bf7f57c)


can anynone tell me what is happening in nosqlmap code

**Comment by icnocop** [comment]
@mrdragonblack did you run `python2 setup.py install` ?

**Comment by Deve-OP** [comment]
convert the code to python 3 works for me

Enter this in the same directory:
2to3 . -w

NOTE: pip install 2to3 module before using it

**Comment by WhiteyCookie** [comment]
That's not a bug, it's coded in python2
