### ISSUE TITLE
CouchDB Attacks Demo Needed

### ISSUE THREAD

**Issue by atom992** [codingo/NoSQLMap#35]
Can anybody give a demo of CouchDB Attacks?

**Comment by tcstool** [comment]
Basically it's just connecting to a CouchDB node with default authentication and being able to enumerate database structure and clone data to your own CouchDB node.  it works very much like the MongoDB attack demos.  Does that help?

**Comment by atom992** [comment]
ok, I see. thanks.
Do you plan to add Couchbase into NOSQL platform?

**Comment by tcstool** [comment]
Yeah someday.  Free time is really, really in short supply right now and
I'm the only developer.

**Comment by atom992** [comment]
ok, Thank you.

**Comment by codingo** [comment]
Resurrecting this issue as I plan on making some further educational content available in the wiki. Although this is quite similar to the mongo attack scenario I feel to prevent this question re-appearing it would be best to make two usage videos.
