### ISSUE TITLE
json support

### ISSUE THREAD

**Issue by blshkv** [codingo/NoSQLMap#38]
Hi, I'm testing a web application which sends and receives JSON objects. That doesn't seem supported since the tools is expecting a traditional parameters. 
Could you add a JSON parser as well?

**Comment by codingo** [comment]
@blshkv I agree, this has value. Other work that needs to take priority first but just replying to let you know that I acknowledge this and will look towards it in the future. Feel free to reply with a reminder if you don't see an update here by February 2018 (sorry for such a long timeframe, lots on the cards so need a healthy buffer!)

**Comment by blshkv** [comment]
honestly, I forgot that filed that bug report. I expected a must faster turn around and it is not really important for me anymore as I found an alternative solution.

**Comment by codingo** [comment]
Sorry about the delay, @tcstool delegated ownership of the repo to me today since I have a but more capacity than him at the moment. There's a bit of a backlog here but we're both going to work through it. If you don't mind my asking, what was the alternative solution (as this will help me to weight the benefit of this feature)?

**Comment by tcstool** [comment]
Yes, I too want to echo my apologies for the delays in responding to and
addressing these issue requests.  I have had several life changes which
resulted in me being completely neglectful of NoSQLMap.  I should have
reached out to find a new maintainer long ago, but never got around to it.
The project is in great hands now and I'm sure will be taken care of!

**Comment by einarjohnson** [comment]
hi guys, this would be a really cool option.

**Comment by JurgenG** [comment]
Any updates here? Also curious to the solution @blshkv  used/found...

**Comment by blshkv** [comment]
Please re-open if you care. This issue is NOT fixed.

**Comment by Reha-sistematik** [comment]
Are you still planning to implement JSON parameters?

**Comment by sagisar1** [comment]
json support is going to be added in the close future?
this would be really helpful

**Comment by fabiand93** [comment]
The project seems dead so maybe not

**Comment by codingo** [comment]
@fabiand93 @Reha-sistematik curious where you're finding utility in this tool. It was quite relevant in years past where you'd still encounter NoSQL Injection in bounties, and in the odd pentest, but I don't believe that's been the case for some time. If you still feel it has application, I can resurrect/overhaul it

**Comment by sagisar1** [comment]
@codingo Who said that there are NoSQL injection bugs in websites today? The fact that there no public evidence to this doesn't say it doesn't exist you feel me?
