### ISSUE TITLE
application crashes if no random string size is entered

### ISSUE THREAD

**Issue by justsly** [codingo/NoSQLMap#45]
if you attack a web app and hit enter to soon instead of entering a random string size the application crashes because "injectSize" cannot be cast to int. maybe you could set a default size if nothing is entered to prevent the app from crashing.

`433        injectSize = raw_input("Baseline test-Enter random string size: ")`
`434        injectString = randInjString(int(injectSize))`
`435        print "Using " + injectString + " for injection testing.\n"`

Keep up the good work.
Cheers

**Comment by codingo** [comment]
Makes sense. I've put this on my roadmap and I'll resolve in a future PR. Will reference this issue at the  time so you can see that it's resolved.

**Comment by Nythiennzo** [comment]
Please have a look at #62 
It's my first time commenting on an issue and using python.
