### ISSUE TITLE
URL Path as Insertion Points

### ISSUE THREAD

**Issue by augustd** [codingo/NoSQLMap#47]
There is no way to specify parts of the URL path itself for testing. For example: 

 ```
https://www.site.com/users/frankie/edit
                               ^ injectable
```

In SQLMap for example this is possible by adding a * to the path to specify a custom insertion point.

**Comment by codingo** [comment]
Makes sense. I'd like to tackle this one but some larger projects ahead of it. Updating this thread to let you know it looks entirely possible, but has to come on the back of some other work first. If this is still outstanding in Dec-2017 feel free to put a reminder in here.

**Comment by SecureThisShit** [comment]
This feature would be very profitable. I would need some function for this as well.
