### ISSUE TITLE
Cannot load headers from backup file

### ISSUE THREAD

**Issue by JeromeNaucelle** [codingo/NoSQLMap#66]
## What's the problem (or question)?
Headers are not loaded when getting the options from a saved file.

## Do you have an idea for a solution?
It's just a minor change to do, i already coded it. i just need a bug fix ID to do the pull request

**Comment by codingo** [comment]
Hi @JeromeNaucelle, just touching base to see how you're going with this pull request

**Comment by codingo** [comment]
Sounds like you might be pushing to master. What you want to do is:

# Create a new branch
```
git branch <branch name>
```

## Checkout your new branch
```
git checkout <branch name from above>
```

You're now on a new branch you can push to your cloned copy of the repository. To do that you can do:

```
git push --set-upstream-origin github.com/JeromeNaucelle
```

After it has pushed then you can come here and open a pull request.

# The Easy Way

If none of that works, or it's a pain, you can always edit it on the website. When you make your first edit at the bottom of the page there will be an option to open a new branch and start a pull request. That will push the changes over.
