### ISSUE TITLE
Stuck in Baseline setup

### ISSUE THREAD

**Issue by heepspray** [codingo/NoSQLMap#70]
## What's the problem (or question)?
I am stuck in the Baseline setup

## How can we reproduce the issue?
1. set options for a web app
2. start NoSQL Web Attack
3. select random string size
4. select format of random string size

## What are the running context details?
OS : Ubuntu server 18

Output:

App is up! Got response length of 24932 and response time of 0.038 seconds.  Starting injection test.

Baseline test-Enter random string size: 2
What format should the random string take?
1-Alphanumeric
2-Letters only
3-Numbers only
4-Email address
Select an option: 1
Select an option: 2
Select an option: 3
Select an option: 4
Select an option: 1
Select an option: 2
Select an option: 3
Select an option: 4
Select an option: 5
Invalid selection.
Select an option: Cry

**Comment by headlessfish** [comment]
I am running into the same issue where it seems to be stuck in "Select an option." I have all the options set, I just can't get past this loop.

**Comment by CaptainFreak** [comment]
PR : #71

**Comment by codingo** [comment]
Resolved with #71
