### ISSUE TITLE
URL down

### ISSUE THREAD

**Issue by fabiand93** [codingo/NoSQLMap#74]
## The url nosqlmap.net it's redirecting to a china stream tv service
Today I tried to reach the website of the project with the url that appear on the description and now the url takes me to a "stream service" in china.

## How can we reproduce the issue?
Just go to the projects url [http://www.nosqlmap.net/](url)

Do you guys forgot to update the domain name?
Are you going to buy another domain for this project?

**Comment by fabiand93** [comment]
A whois request gives me this: 
Domain Name: NOSQLMAP.NET
Registry Domain ID: 2337859069_DOMAIN_NET-VRSN
Registrar WHOIS Server: whois.namebright.com
Registrar URL: http://www.NameBright.com
Updated Date: 2018-12-02T02:58:09Z
Creation Date: 2018-11-28T19:34:04Z
Registry Expiry Date: 2019-11-28T19:34:04Z
Registrar: DropCatch.com 922 LLC
Registrar IANA ID: 2681
Registrar Abuse Contact Email:
Registrar Abuse Contact Phone:
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Name Server: JM1.DNS.COM
Name Server: JM2.DNS.COM
DNSSEC: unsigned
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of whois database: 2019-01-02T16:37:09Z <<<

**Comment by codingo** [comment]
@fabiand93 good pickup, looks like this expired in the shuffle (baby on the way currently). I'll make a move to another domain name shortly, and plan on removing references to the existing one today.
