### ISSUE TITLE
POST Request Attack Error in Interactive Mode

### ISSUE THREAD

**Issue by carlosmgc** [codingo/NoSQLMap#83]
## What's the problem (or question)?
When using nosqlmap in interactive mode, the web attack will fail when using HTTP POST method due to the postParameter variable not being defined.

## Do you have an idea for a solution?

To solve the issue, replace line 340 in nosqlmap.py from this:

> build_post_data(postDataIn)

To this:

> postData = build_post_data(postDataIn)

## How can we reproduce the issue?
1. Run nosqlmap
2. Select option 1 to set options
3. Populate all needed options for Web attacks
4. Set option 6 to post and enter the post patameters
5. Go back to main menu
6. Select option 3 for web attacks

At this point the app will fail with message:
NameError: global name 'postData' is not defined

## What are the running context details?
Kali linux running stand alone cloned from github.

**Comment by happyren** [comment]
I fixed this issue by modifying line 340

```python
postData =  build_post_data(postDataIn)
```

@codingo

**Comment by codingo** [comment]
Closed with #85
