### ISSUE TITLE
NoSQLMap Post Parametre Error

### ISSUE THREAD

**Issue by secfb** [codingo/NoSQLMap#84]
https://192.168.2.100/cgi-bin/mongo/2.2.3/dbparse.py my url 
Normal Post Data
CompanyName=aa
NoSQLMap POST Parametre
CompanyName,aa
<img width="731" alt="2" src="https://user-images.githubusercontent.com/38748801/58312915-04b69b80-7e15-11e9-9e55-fee2662e281c.png">

I get the following error. What am I doing wrong.
<img width="1002" alt="3" src="https://user-images.githubusercontent.com/38748801/58312993-3a5b8480-7e15-11e9-8d55-bbd5ce9e77a4.png">

**Comment by codingo** [comment]
Closes with #85
