### ISSUE TITLE
Migrate to python 3

### ISSUE THREAD

**Issue by ellcs** [codingo/NoSQLMap#97]
Hello there! 
Thank you for working on this project! Python 2 reached end of life at the end of 2019. So NoSQLMap should really migrate to python 3.

Best regards, ellcs

**Comment by blshkv** [comment]
@ellcs can you please reopen the issue?

**Comment by ellcs** [comment]
@blshkv is commenting enough, to reopen it?

**Comment by ellcs** [comment]
> @blshkv is commenting enough, to reopen it?

Guess no. I will copy it.

**Comment by blshkv** [comment]
:(
